services:
  - type: web
    name: monpolymet-api
    env: node
    region: oregon
    plan: free
    rootDir: Monpolymet-API
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
